all: testes

lab02:
	gcc -std=c99 -Wall -Werror -g -lm lab02.c -o lab02

testes: lab02
	./lab02 < ./lab02testes/in/t1_in.txt > ./lab02testes/meuout/t1_meuout.txt
	./lab02 < ./lab02testes/in/t2_in.txt > ./lab02testes/meuout/t2_meuout.txt
	./lab02 < ./lab02testes/in/t3_in.txt > ./lab02testes/meuout/t3_meuout.txt
	./lab02 < ./lab02testes/in/t4_in.txt > ./lab02testes/meuout/t4_meuout.txt
	./lab02 < ./lab02testes/in/t5_in.txt > ./lab02testes/meuout/t5_meuout.txt
	./lab02 < ./lab02testes/in/t6_in.txt > ./lab02testes/meuout/t6_meuout.txt
	./lab02 < ./lab02testes/in/t7_in.txt > ./lab02testes/meuout/t7_meuout.txt
	./lab02 < ./lab02testes/in/t8_in.txt > ./lab02testes/meuout/t8_meuout.txt
	./lab02 < ./lab02testes/in/t9_in.txt > ./lab02testes/meuout/t9_meuout.txt
	./lab02 < ./lab02testes/in/t10_in.txt > ./lab02testes/meuout/t10_meuout.txt
	./lab02 < ./lab02testes/in/t11_in.txt > ./lab02testes/meuout/t11_meuout.txt
	./lab02 < ./lab02testes/in/t12_in.txt > ./lab02testes/meuout/t12_meuout.txt
	./lab02 < ./lab02testes/in/t13_in.txt > ./lab02testes/meuout/t13_meuout.txt
	./lab02 < ./lab02testes/in/t14_in.txt > ./lab02testes/meuout/t14_meuout.txt
	./lab02 < ./lab02testes/in/t15_in.txt > ./lab02testes/meuout/t15_meuout.txt
	./lab02 < ./lab02testes/in/t16_in.txt > ./lab02testes/meuout/t16_meuout.txt
	./lab02 < ./lab02testes/in/t17_in.txt > ./lab02testes/meuout/t17_meuout.txt
	./lab02 < ./lab02testes/in/t18_in.txt > ./lab02testes/meuout/t18_meuout.txt
	./lab02 < ./lab02testes/in/t19_in.txt > ./lab02testes/meuout/t19_meuout.txt
	./lab02 < ./lab02testes/in/t20_in.txt > ./lab02testes/meuout/t20_meuout.txt
	diff ./lab02testes/out/t1_out.txt ./lab02testes/meuout/t1_meuout.txt > ./lab02testes/resultados/t1_resultado.txt
	diff ./lab02testes/out/t2_out.txt ./lab02testes/meuout/t2_meuout.txt > ./lab02testes/resultados/t2_resultado.txt
	diff ./lab02testes/out/t3_out.txt ./lab02testes/meuout/t3_meuout.txt > ./lab02testes/resultados/t3_resultado.txt
	diff ./lab02testes/out/t4_out.txt ./lab02testes/meuout/t4_meuout.txt > ./lab02testes/resultados/t4_resultado.txt
	diff ./lab02testes/out/t5_out.txt ./lab02testes/meuout/t5_meuout.txt > ./lab02testes/resultados/t5_resultado.txt
	diff ./lab02testes/out/t6_out.txt ./lab02testes/meuout/t6_meuout.txt > ./lab02testes/resultados/t6_resultado.txt
	diff ./lab02testes/out/t7_out.txt ./lab02testes/meuout/t7_meuout.txt > ./lab02testes/resultados/t7_resultado.txt
	diff ./lab02testes/out/t8_out.txt ./lab02testes/meuout/t8_meuout.txt > ./lab02testes/resultados/t8_resultado.txt
	diff ./lab02testes/out/t9_out.txt ./lab02testes/meuout/t9_meuout.txt > ./lab02testes/resultados/t9_resultado.txt
	diff ./lab02testes/out/t10_out.txt ./lab02testes/meuout/t10_meuout.txt > ./lab02testes/resultados/t10_resultado.txt
	diff ./lab02testes/out/t11_out.txt ./lab02testes/meuout/t11_meuout.txt > ./lab02testes/resultados/t11_resultado.txt
	diff ./lab02testes/out/t12_out.txt ./lab02testes/meuout/t12_meuout.txt > ./lab02testes/resultados/t12_resultado.txt
	diff ./lab02testes/out/t13_out.txt ./lab02testes/meuout/t13_meuout.txt > ./lab02testes/resultados/t13_resultado.txt
	diff ./lab02testes/out/t14_out.txt ./lab02testes/meuout/t14_meuout.txt > ./lab02testes/resultados/t14_resultado.txt
	diff ./lab02testes/out/t15_out.txt ./lab02testes/meuout/t15_meuout.txt > ./lab02testes/resultados/t15_resultado.txt
	diff ./lab02testes/out/t16_out.txt ./lab02testes/meuout/t16_meuout.txt > ./lab02testes/resultados/t16_resultado.txt
	diff ./lab02testes/out/t17_out.txt ./lab02testes/meuout/t17_meuout.txt > ./lab02testes/resultados/t17_resultado.txt
	diff ./lab02testes/out/t18_out.txt ./lab02testes/meuout/t18_meuout.txt > ./lab02testes/resultados/t18_resultado.txt
	diff ./lab02testes/out/t19_out.txt ./lab02testes/meuout/t19_meuout.txt > ./lab02testes/resultados/t19_resultado.txt
	diff ./lab02testes/out/t20_out.txt ./lab02testes/meuout/t20_meuout.txt > ./lab02testes/resultados/t20_resultado.txt
